- name: make sure ansible_merge_vars is installed
  pip:
    name: ansible_merge_vars
    virtualenv: /usr/local/bin/ansible
    virtualenv_site_packages: yes

- name: Merge os variables
  merge_vars:
    suffix_to_merge: ossettings__to_merge
    merged_var_name: merged_system_settings
    expected_type: 'dict'

- name: Merge network variables
  merge_vars:
    suffix_to_merge: networksettings__to_merge
    merged_var_name: merged_network_settings
    expected_type: 'dict'

- name: Install nmcli
  yum:
    name: NetworkManager-glib
    state: latest
  when: merged_network_settings.eth0_mtu is defined

- name: Set MTU
  nmcli:
    conn_name: eth0
    mtu: "{{ merged_network_settings.eth0_mtu }}"
    type: ethernet
    state: present
  when: merged_network_settings.eth0_mtu is defined

- name: Set sysctl settings
  sysctl:
    ignoreerrors: "{{ sysctl.ignoreerrors | default(default_sysctl_ignoreerrors) }}"
    name: "{{ sysctl.name }}"
    reload: "{{ sysctl.reload | default(default_sysctl_reload) }}"
    state: "{{ sysctl.state | default(default_sysctl_state) }}"
    sysctl_file: "{{ sysctl.sysctl_file | default(default_sysctl_sysctl_file) }}"
    sysctl_set: "{{ sysctl.sysctl_set | default(default_sysctl_sysctl_set) }}"
    value: "{{ sysctl.value }}" 
  with_items: "{{ merged_system_settings }}"
  loop_control:
    loop_var: sysctl
  when: merged_system_settings is defined
